#!/usr/bin/env bash

# Obtain the directory of the script
path="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)"
# Extract the filename of the script
filename=$(basename "$0")

brown='\e[0;33m'
reset='\033[0m'
if [ "$#" -lt 4 ]; then
    echo -e "Usage: ${brown}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
    exit 1
fi

# echo "Transfering $1 to $2 with username $3 and SSH key $4"
scp -o StrictHostKeyChecking=no -i "$4" "$path"/"$1" "$3"@"$2":~/
