#!/usr/bin/env bash

# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# Ping the IP address 5 times

if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1"

if [ $? -eq 0 ]; then
    echo "IP address is alive"
else
    echo "IP address is unreachable"
fi
