#!/usr/bin/env bash
# Bash script that displays a list of currently running processes.Display in a user-oriented format
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
ps aux | awk '{print $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}' | sort -k 2 -n -r
